version: "3.8"
services:
  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  # api:
  #   image: node:latest
  #   container_name: api
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   volumes:
  #     - .:/src/app
  #   working_dir: /src/app
  #   command: yarn start
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
